server:
  port: 9393

spring:
  profiles:
    active: default
  redis:
    port: 6379
    host: localhost
    pool.maxIdle: 8
    pool.minIdle: 0
    pool.maxActive: 8
    pool.maxWait: -1

---
xd:
  analytics:
    redis:
      backOffInitialInterval:    1000
      backOffMaxInterval:        10000
      backOffMultiplier:         2.0
      maxAttempts:               5

---
security:
  basic:
    enabled: false

management:
  security:
    enabled: false

endpoints:
  metrics:
    id: appmetrics
